kind: pipeline
name: default

steps:
  - name: install
    image: node:12
    pull: always
    environment:
      CYPRESS_CACHE_FOLDER: .cypress
    commands:
      - node -v
      - npm -v
      - npm ci

  - name: test
    image: cypress/browsers:node12.18.0-chrome83-ff77
    pull: always
    environment:
      CYPRESS_CACHE_FOLDER: .cypress
    commands:
      - npm run test

  - name: build
    image: node:12
    pull: always
    environment:
      DIRECTUS_URL:
        from_secret: directus_url
      DIRECTUS_TOKEN:
        from_secret: directus_token
    commands:
      - npm run export:production
    when:
      branch:
        - master

  - name: deploy
    image: cupcakearmy/drone-deploy
    pull: always
    environment:
      PLUGIN_KEY:
        from_secret: key
    settings:
      host: love-foundation.org
      user: root
      port: 1312
      target: /srv/new
      sources:
        - ./__sapper__/export
        - ./docker-compose.prod.yml
      commands:
        - docker-compose -f docker-compose.prod.yml up -d --build
    when:
      branch:
        - master
