type: "docker"
kind: pipeline
name: build-and-deploy

steps:
  - name: install
    image: node:20
    pull: always
    commands:
      - node -v
      - npm -v
      - npm ci

  - name: test
    image: cypress/included:13.7.0
    pull: always
    environment:
      VITE_DIRECTUS_URL:
        from_secret: directus_url_new
      VITE_DIRECTUS_TOKEN:
        from_secret: directus_token_new
    commands:
      - npm run test
    when:
      branch:
        exclude:
          - master

  - name: build staging
    image: node:20
    pull: always
    environment:
      VITE_DIRECTUS_URL:
        from_secret: directus_url_new
      VITE_DIRECTUS_TOKEN:
        from_secret: directus_token_new
      VITE_APP_MODE: staging
    commands:
      - npm run build:staging
    when:
      branch:
        exclude:
          - master

  - name: deploy staging
    image: appleboy/drone-scp
    pull: always
    settings:
      host: love-foundation.org
      username: lfdeploy
      port:
        from_secret: port
      key:
        from_secret: key
      passphrase:
        from_secret: passphrase
      target: /srv/lf/website/staging/deploy
      overwrite: true
      source:
        - ./build
        - ./node_modules
        - ./package.json
        - ./package-lock.json
        - ./src
        - ./Dockerfile
        - ./docker-compose.staging.yml
    when:
      branch:
        exclude:
          - master

  - name: restart staging server
    image: appleboy/drone-ssh
    pull: always
    settings:
      command_timeout: 2m
      host: love-foundation.org
      username: lfdeploy
      port:
        from_secret: port
      key:
        from_secret: key
      passphrase:
        from_secret: passphrase
      script:
        - cd /srv/lf/website/staging
        - rsync -ravI ./deploy/ . --delete-after --filter="P .env"
        - ls -al ./deploy
        - rm -rf ./deploy
        - docker-compose -f docker-compose.staging.yml up -d --build
    when:
      branch:
        exclude:
          - master

  - name: build production
    image: node:20
    pull: always
    environment:
      VITE_DIRECTUS_URL:
        from_secret: directus_url_new
      VITE_DIRECTUS_TOKEN:
        from_secret: directus_token_new
    commands:
      - npm run build
    when:
      branch:
        - master

  - name: deploy production
    image: appleboy/drone-scp
    pull: always
    settings:
      host: love-foundation.org
      user: lfdeploy
      key:
        from_secret: key
      passphrase:
        from_secret: passphrase
      port:
        from_secret: port
      target: /srv/lf/website/prod/deploy
      source:
        - ./build
        - ./docker-compose.prod.yml
      overwrite: true
    when:
      branch:
        - master

  - name: restart production server
    image: appleboy/drone-ssh
    pull: always
    settings:
      command_timeout: 2m
      host: love-foundation.org
      username: lfdeploy
      port:
        from_secret: port
      key:
        from_secret: key
      passphrase:
        from_secret: passphrase
      script:
        - pwd
        - cd /srv/lf/website/prod
        - pwd
        - rsync -ravI ./deploy/ . --delete-after
        - rm -rf ./deploy
        - docker-compose -f docker-compose.prod.yml up -d --build
    when:
      branch:
        - master

trigger:
  event:
    include:
      - push
      - pull_request

---
type: "docker"
kind: pipeline
name: directus-build-and-deploy

steps:
  - name: install
    image: node:20
    pull: always
    environment:
      CYPRESS_CACHE_FOLDER: .cypress
    commands:
      - node -v
      - npm -v
      - npm ci

  - name: test
    image: cypress/included:13.7.0
    pull: always
    environment:
      CYPRESS_CACHE_FOLDER: .cypress
      VITE_DIRECTUS_URL:
        from_secret: directus_url_new
      VITE_DIRECTUS_TOKEN:
        from_secret: directus_token_new
    commands:
      - npm run test

  - name: build production
    image: node:20
    pull: always
    environment:
      VITE_DIRECTUS_URL:
        from_secret: directus_url_new
      VITE_DIRECTUS_TOKEN:
        from_secret: directus_token_new
      NODE_ENV: production
    commands:
      - npm run build

  - name: deploy production
    image: appleboy/drone-scp
    pull: always
    settings:
      host: love-foundation.org
      user: lfdeploy
      key:
        from_secret: key
      passphrase:
        from_secret: passphrase
      port:
        from_secret: port
      target: /srv/lf/website/prod/deploy
      source:
        - ./build
        - ./docker-compose.prod.yml
      overwrite: true

  - name: restart production server
    image: appleboy/drone-ssh
    pull: always
    settings:
      command_timeout: 2m
      host: love-foundation.org
      username: lfdeploy
      port:
        from_secret: port
      key:
        from_secret: key
      passphrase:
        from_secret: passphrase
      script:
        - cd /srv/lf/website/prod
        - rsync -ravI ./deploy/ . --delete-after
        - rm -rf ./deploy
        - docker-compose -f docker-compose.prod.yml up -d --build

trigger:
  event:
    include:
      - cron
