kind: pipeline
name: build-and-deploy

steps:
  - name: install
    image: node:16
    pull: always
    environment:
      CYPRESS_CACHE_FOLDER: .cypress
    commands:
      - node -v
      - npm -v
      - npm ci

  - name: test
    image: cypress/included:8.3.0
    pull: always
    environment:
      CYPRESS_CACHE_FOLDER: .cypress
      VITE_DIRECTUS_URL:
        from_secret: directus_url_new
      VITE_DIRECTUS_TOKEN:
        from_secret: directus_token_new
    commands:
      - npm run test
    when:
      branch:
        exclude:
          - master

  - name: build staging
    image: node:16
    pull: always
    environment:
      VITE_DIRECTUS_URL:
        from_secret: directus_url_new
      VITE_DIRECTUS_TOKEN:
        from_secret: directus_token_new
      VITE_APP_MODE: staging
    commands:
      - npm run build:staging
    when:
      branch:
        exclude:
          - master

  - name: deploy staging
    image: cupcakearmy/drone-deploy
    pull: always
    settings:
      host: love-foundation.org
      user: lfdeploy
      port:
        from_secret: port
      key:
        from_secret: key
      target: /srv/lf/website/staging
      sources:
        - ./build
        - ./node_modules
        - ./package.json
        - ./package-lock.json
        - ./src
        - ./Dockerfile
        - ./docker-compose.staging.yml
      commands:
        - docker-compose -f docker-compose.staging.yml up -d --build
    when:
      branch:
        exclude:
          - master

  - name: build production
    image: node:16
    pull: always
    environment:
      VITE_DIRECTUS_URL:
        from_secret: directus_url_new
      VITE_DIRECTUS_TOKEN:
        from_secret: directus_token_new
    commands:
      - npm run build
    when:
      branch:
        - master

  - name: deploy production
    image: cupcakearmy/drone-deploy
    pull: always
    environment:
      PLUGIN_KEY:
        from_secret: key
    settings:
      host: love-foundation.org
      user: lfdeploy
      key:
        from_secret: key
      port:
        from_secret: port
      target: /srv/lf/website/prod
      sources:
        - ./build
        - ./docker-compose.prod.yml
      commands:
        - docker-compose -f docker-compose.prod.yml up -d --build
    when:
      branch:
        - master

trigger:
  event:
    include:
      - push
      - pull_request

---
kind: pipeline
name: directus-build-and-deploy

steps:
  - name: install
    image: node:16
    pull: always
    environment:
      CYPRESS_CACHE_FOLDER: .cypress
    commands:
      - node -v
      - npm -v
      - npm ci

  - name: test
    image: cypress/included:8.3.0
    pull: always
    environment:
      CYPRESS_CACHE_FOLDER: .cypress
      VITE_DIRECTUS_URL:
        from_secret: directus_url_new
      VITE_DIRECTUS_TOKEN:
        from_secret: directus_token_new
    commands:
      - npm run test

  - name: build production
    image: node:16
    pull: always
    environment:
      VITE_DIRECTUS_URL:
        from_secret: directus_url_new
      VITE_DIRECTUS_TOKEN:
        from_secret: directus_token_new
      NODE_ENV: production
    commands:
      - npm run build

  - name: deploy production
    image: cupcakearmy/drone-deploy
    pull: always
    environment:
      PLUGIN_KEY:
        from_secret: key
    settings:
      host: love-foundation.org
      user: lfdeploy
      key:
        from_secret: key
      port:
        from_secret: port
      target: /srv/lf/website/prod
      sources:
        - ./build
        - ./docker-compose.prod.yml
      commands:
        - docker-compose -f docker-compose.prod.yml up -d --build

trigger:
  event:
    include:
      - cron
