kind: pipeline
name: build-and-deploy

steps:
  - name: install
    image: node:12
    pull: always
    environment:
      CYPRESS_CACHE_FOLDER: .cypress
    commands:
      - node -v
      - npm -v
      - npm ci

  - name: test
    image: cypress/browsers:node12.18.0-chrome83-ff77
    pull: always
    environment:
      CYPRESS_CACHE_FOLDER: .cypress
      DIRECTUS_URL:
        from_secret: directus_url_new
      DIRECTUS_TOKEN:
        from_secret: directus_token_new
    commands:
      - npm run test

  - name: build staging
    image: node:12
    pull: always
    environment:
      DIRECTUS_URL:
        from_secret: directus_url_new
      DIRECTUS_TOKEN:
        from_secret: directus_token_new
      NODE_ENV: staging
    commands:
      - npm run build
    when:
      branch:
        exclude:
          - master

  - name: deploy staging
    image: cupcakearmy/drone-deploy
    pull: always
    environment:
      PLUGIN_KEY:
        from_secret: key
    settings:
      host: love-foundation.org
      user: root
      port: 1312
      target: /srv/lf/website/staging
      sources:
        - ./__sapper__/build
        - ./static
        - ./src
        - ./node_modules
        - ./Dockerfile
        - ./docker-compose.staging.yml
      commands:
        - docker-compose -f docker-compose.staging.yml up -d --build
    when:
      branch:
        exclude:
          - master

  - name: build production
    image: node:12
    pull: always
    environment:
      DIRECTUS_URL:
        from_secret: directus_url_new
      DIRECTUS_TOKEN:
        from_secret: directus_token_new
      NODE_ENV: production
    commands:
      - npm run export:production
    when:
      branch:
        - master

  - name: deploy production
    image: cupcakearmy/drone-deploy
    pull: always
    environment:
      PLUGIN_KEY:
        from_secret: key
    settings:
      host: love-foundation.org
      user: root
      port: 1312
      target: /srv/lf/website/prod
      sources:
        - ./__sapper__/export
        - ./docker-compose.prod.yml
      commands:
        - docker-compose -f docker-compose.prod.yml up -d --build
    when:
      branch:
        - master

trigger:
  event:
    include:
      - push
      - pull_request

---
kind: pipeline
name: directus-build-and-deploy

steps:
  - name: install
    image: node:12
    pull: always
    environment:
      CYPRESS_CACHE_FOLDER: .cypress
    commands:
      - node -v
      - npm -v
      - npm ci

  - name: test
    image: cypress/browsers:node12.18.0-chrome83-ff77
    pull: always
    environment:
      CYPRESS_CACHE_FOLDER: .cypress
      DIRECTUS_URL:
        from_secret: directus_url_new
      DIRECTUS_TOKEN:
        from_secret: directus_token_new
    commands:
      - npm run test

  - name: build production
    image: node:12
    pull: always
    environment:
      DIRECTUS_URL:
        from_secret: directus_url_new
      DIRECTUS_TOKEN:
        from_secret: directus_token_new
      NODE_ENV: production
    commands:
      - npm run export:production

  - name: deploy production
    image: cupcakearmy/drone-deploy
    pull: always
    environment:
      PLUGIN_KEY:
        from_secret: key
    settings:
      host: love-foundation.org
      user: root
      port: 1312
      target: /srv/lf/website/prod
      sources:
        - ./__sapper__/export
        - ./docker-compose.prod.yml
      commands:
        - docker-compose -f docker-compose.prod.yml up -d --build

trigger:
  event:
    include:
      - custom
