kind: pipeline
name: default

steps:
  - name: build
    image: node:12
    pull: always
    commands:
      - node -v
      - npm -v
      - npm install
      - npm run export

  - name: deploy
    image: cupcakearmy/drone-deploy
    pull: always
    environment:
      PLUGIN_KEY:
        from_secret: key
    settings:
      host: love-foundation.org
      user: root
      port: 1312
      target: /srv/new
      sources:
        - ./__sapper__/export
        - ./docker-compose.prod.yml
      commands:
        - docker-compose -f docker-compose.prod.yml up -d --build
    when:
      event:
        exclude:
          - pull_request