kind: pipeline
name: default

cache-common: &cache-common
  image: meltwater/drone-cache
  environment:
    PLUGIN_ACCESS_KEY: 3R3u3XVKmNcPWCpzqV6R9vgtdgw6tk3Q
    PLUGIN_SECRET_KEY:
      from_secret: minio
  pull: true

cache-settings: &cache-settings
  bucket: cache
  region: main
  path_style: true
  endpoint: https://cache.love-foundation.org
  mount:
    - 'node_modules' 

steps:
  - name: restore-cache
    <<: *cache-common
    settings:
      <<: *cache-settings
      restore: true

  - name: install
    image: node:12
    pull: always
    commands:
      - node -v
      - npm -v
      - npm install
  
  - name: rebuild-cache
    <<: *cache-common
    settings:
      <<: *cache-settings
      rebuild: true 

  - name: build
    image: node:12
    pull: always
    commands:
      - npm run export -- --timeout 15000

    environment:
      PLUGIN_KEY:
        from_secret: key
    settings:
      host: love-foundation.org
      user: root
      port: 1312
      target: /srv/new
      sources:
        - ./__sapper__/export
        - ./docker-compose.prod.yml
      commands:
        - docker-compose -f docker-compose.prod.yml up -d --build
    when:
      event:
        exclude:
          - pull_request