kind: pipeline
name: default

cache-common: &cache-common
  image: meltwater/drone-cache
  environment:
    PLUGIN_ACCESS_KEY: 3R3u3XVKmNcPWCpzqV6R9vgtdgw6tk3Q
    PLUGIN_SECRET_KEY:
      from_secret: minio
  pull: true

cache-settings: &cache-settings
  bucket: cache
  region: main
  path_style: true
  endpoint: https://cache.love-foundation.org
  mount:
    - 'node_modules'
    - '/root/.cache/Cypress'

steps:
  # - name: restore-cache
  #   <<: *cache-common
  #   settings:
  #     <<: *cache-settings
  #     restore: true

  - name: install
    image: node:12
    pull: always
    environment:
      CYPRESS_CACHE_FOLDER: ./cypress
    commands:
      - node -v
      - npm -v
      - npm ci
      - npx cypress install

  # - name: rebuild-cache
  #   <<: *cache-common
  #   settings:
  #     <<: *cache-settings
  #     rebuild: true

  - name: test
    image: node:12
    pull: always
    environment:
      CYPRESS_CACHE_FOLDER: ./cypress
    commands:
      - npm run test

  - name: build
    image: node:12
    pull: always
    environment:
      DIRECTUS_URL:
        from_secret: directus_url
      DIRECTUS_TOKEN:
        from_secret: directus_token
    commands:
      - npm run export:production

  - name: deploy
    image: cupcakearmy/drone-deploy
    pull: always
    environment:
      PLUGIN_KEY:
        from_secret: key
    settings:
      host: love-foundation.org
      user: root
      port: 1312
      target: /srv/new
      sources:
        - ./__sapper__/export
        - ./docker-compose.prod.yml
      commands:
        - docker-compose -f docker-compose.prod.yml up -d --build
    when:
      event:
        exclude:
          - pull_request
