version: '3.7'

networks:
    proxy:
      external: true

services:
    app:
        build: .
        volumes:
            - ./__sapper__:/app/__sapper__
            - ./static:/app/static
        networks:
            - proxy
            labels:
            - "traefik.enable=true"
            - "traefik.port=3000"
            - "traefik.docker.network=proxy"
            - "traefik.backend=webnew"
            - "traefik.frontend.rule=Host:new.love-foundation.org"