version: '3.7'

networks:
  proxy:
    external: true

services:
  app:
    build: .
    restart: unless-stopped
    env_file:
      - /srv/lf/website/staging/.env
    ports:
      - 3000:3000
    volumes:
      - .:/app
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.services.lf-website-staging.loadbalancer.server.port=3000
      - traefik.http.routers.lf-website-staging.rule=Host(`staging.love-foundation.org`)
      - traefik.http.routers.lf-website-staging.entrypoints=secure
      - traefik.http.routers.lf-website-staging.tls.certresolver=le
