version: '3.7'

networks:
    proxy:
      external: true

services:
    app:
        image: cupcakearmy/static
        restart: unless-stopped
        volumes:
            - ./__sapper__/export:/srv
        networks:
            - proxy
        labels:
            - "traefik.enable=true"
            - "traefik.port=80"
            - "traefik.docker.network=proxy"
            - "traefik.backend=webnew-staging"
            - "traefik.frontend.rule=Host:staging.love-foundation.org"
