version: '3.7'

networks:
    proxy:
      external: true

services:
    app:
        build: .
        restart: unless-stopped
        env_file:
            - ./.env
        ports:
            - 3000:3000
        volumes:
            - .:/app
        networks:
            - proxy
        labels:
            - "traefik.enable=true"
            - "traefik.port=3000"
            - "traefik.docker.network=proxy"
            - "traefik.backend=webnew-staging"
            - "traefik.frontend.rule=Host:staging.love-foundation.org"
